settings:
  title: 'Status Page'
  url: 'hulu365.ggff.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: FreeAskInternet
    name: FreeAskInternet  onrender
    description: 'FreeAskInternet'
    url: 'https://freeaskinternet-5pnf.onrender.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: home-xw-com
    name: The xw home
    url: 'https://endpoint.xiaowangtech.com/xw-moonlit/moonlit/dashboard/calendar'
    method: GET
    expectStatus: 200

  
  - id: guangdong-chinatax-gov
    name: The guangdong chinatax
    url: 'https://dppt.guangdong.chinatax.gov.cn:8443/kpfw/fpcx/v1/fpcxByFpzs'
    method: GET
    expectStatus: 200

  - id: metaso-free-api
    name: The metaso free api
    url: 'https://metaso-free-api-mi8l.onrender.com'
    method: GET
    expectStatus: 200

  - id: searxng
    name: The searxng
    url: 'https://searxng-c9r5.onrender.com'
    method: GET
    expectStatus: 200
  

  - id: coze-discord-proxy
    name: The coze discord proxy
    url: 'https://coze-discord-proxy-iknu.onrender.com'
    method: GET
    expectStatus: 200

    
  

  - id: lobe-chat
    name: The lobe chat
    url: 'https://lobe-chat-7g5k.onrender.com'
    method: GET
    expectStatus: 200

  

  - id: one-api
    name: The one api
    url: 'https://one-api-latest-dq8m.onrender.com'
    method: GET
    expectStatus: 200

    
  

  - id: ai-pro
    name: The aipro
    url: 'https://aipro2api.onrender.com'
    method: GET
    expectStatus: 200
